# Generated by Django 3.1.3 on 2020-11-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0010_auto_20201113_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='1605274223VaEpTI8U65jA', max_length=128, unique=True)),
                ('title', models.CharField(default='待打卡任务', max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('icon_theme', models.CharField(default='star', max_length=64)),
                ('color_theme', models.CharField(default='0xffff', max_length=64)),
                ('cTime', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '打卡',
                'verbose_name_plural': '打卡',
                'ordering': ['-cTime'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ClockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bind_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.clockinitem', to_field='_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'bind_item', 'timestamp')},
            },
        ),
    ]
