# Generated by Django 3.1.3 on 2020-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_auto_20201113_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1605276498VvF1aj03oeE5', max_length=128, unique=True),
        ),
    ]
