# Generated by Django 3.1.3 on 2020-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_auto_20201113_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1605324655cmxKhMCE0dLZ', max_length=128, unique=True),
        ),
    ]
