# Generated by Django 3.1.3 on 2020-11-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20201124_1854'),
        ('clock', '0008_auto_20201114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1606215260cv4u9tPTL1Aw', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='WeekRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('week_start', models.DateField()),
                ('week_num', models.IntegerField(default=47)),
                ('bind_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.clockinitem', to_field='_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '周完成记录',
                'verbose_name_plural': '周完成记录',
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'bind_item', 'week_num')},
            },
        ),
    ]
