# Generated by Django 3.1.3 on 2020-11-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0010_auto_20201124_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='16062741717bfl1kmtQBPT', max_length=128, unique=True),
        ),
    ]
