# Generated by Django 3.1.3 on 2020-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0013_auto_20201126_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='160640652982AW6MOTu1tL', max_length=128, unique=True),
        ),
    ]
