# Generated by Django 3.1.3 on 2020-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0015_auto_20201127_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1606454919q2cIrHBCpZ4K', max_length=128, unique=True),
        ),
    ]
