# Generated by Django 3.1.3 on 2020-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0016_auto_20201127_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1606455320j5aKkp0OoqMe', max_length=128, unique=True),
        ),
    ]
