# Generated by Django 3.1.3 on 2020-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0017_auto_20201127_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinitem',
            name='_id',
            field=models.CharField(default='1606535582BHGweQbxlOL4', max_length=128, unique=True),
        ),
    ]
