# Generated by Django 3.1.3 on 2020-11-13 06:25

import User.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='轻记用户_8XBparsYJ5y0', max_length=64)),
                ('password', models.CharField(default='Lose weight', max_length=512)),
                ('profile', models.ImageField(null=True, upload_to=User.models.user_directory_path)),
                ('cTime', models.DateField(default=datetime.datetime(2020, 11, 13, 6, 25, 9, 107083, tzinfo=utc))),
                ('gender', models.CharField(choices=[('female', 'Female')], default='male', max_length=10)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-cTime'],
            },
        ),
    ]
