# Generated by Django 3.1.3 on 2020-11-13 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='cTime',
            field=models.DateField(default=datetime.datetime(2020, 11, 13, 6, 39, 1, 389342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_dg5JXVMo0AYP', max_length=64),
        ),
    ]
