# Generated by Django 3.1.3 on 2020-11-13 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201113_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cTime',
            field=models.DateField(default=datetime.datetime(2020, 11, 13, 9, 42, 48, 449945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_JwZILAhKY9VG', max_length=64),
        ),
    ]
