# Generated by Django 3.1.3 on 2020-11-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20201113_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_hJIXY8ZuOvWS', max_length=64),
        ),
    ]
