# Generated by Django 3.1.3 on 2020-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201113_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_F9isHt4gpy1X', max_length=64),
        ),
    ]
