# Generated by Django 3.1.3 on 2020-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_auto_20201113_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_qf7J3OjNiByD', max_length=64),
        ),
    ]
