# Generated by Django 3.1.3 on 2020-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20201113_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_iXY3KJchfMF2', max_length=64),
        ),
    ]
