# Generated by Django 3.1.3 on 2020-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20201113_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_rG845DRtZCyK', max_length=64),
        ),
    ]
