# Generated by Django 3.1.3 on 2020-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_auto_20201114_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_Onq0sbJ9pt8l', max_length=64),
        ),
    ]
