# Generated by Django 3.1.3 on 2020-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_auto_20201114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_GyWYZcd0VKOB', max_length=64),
        ),
    ]
