# Generated by Django 3.1.3 on 2020-11-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_auto_20201125_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_ReCyQrBA4E3S', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(default='./static/profile/default.png', max_length=512),
        ),
    ]
