# Generated by Django 3.1.3 on 2020-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_auto_20201126_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_jm1su3ioKOML', max_length=64),
        ),
    ]
