# Generated by Django 3.1.3 on 2020-11-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20201127_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_jXn1xuaJeN93', max_length=64),
        ),
    ]
