# Generated by Django 3.1.3 on 2020-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_auto_20201127_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='轻记用户_ODFyk6PawG7U', max_length=64),
        ),
    ]
