# Generated by Django 3.1.3 on 2020-11-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0029_auto_20201127_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('txt_content', models.TextField(default='...')),
                ('image_list', models.CharField(default='', max_length=2048)),
                ('type', models.CharField(choices=[('sport', '健身'), ('food', '饮食'), ('experience', '经验')], default='sport', max_length=64)),
                ('secondary_type', models.CharField(choices=[('run', '跑步'), ('air', '有氧'), ('no_air', '无氧'), ('hit', 'HIT运动'), ('low_calorie', '低卡'), ('fit_meal', '健身三餐'), ('diy_meal', '自制美食'), ('contrast', '对比'), ('long_way', '历程'), ('daily', '日常')], default='run', max_length=64)),
                ('collections', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
