# Generated by Django 3.1.3 on 2020-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdynamic',
            options={'ordering': ['-timestamp'], 'verbose_name': '用户动态', 'verbose_name_plural': '用户动态'},
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='id',
            field=models.CharField(default='2020-11-27 13:35:20.854942', max_length=128, primary_key=True, serialize=False),
        ),
    ]
