# Generated by Django 3.1.3 on 2020-11-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0027_auto_20201126_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('breakfast', models.CharField(default='', max_length=1024, null=True)),
                ('lunch', models.CharField(default='', max_length=1024, null=True)),
                ('dinner', models.CharField(default='', max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '每日饮食记录',
                'verbose_name_plural': '每日饮食记录',
                'ordering': ['-day'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
